#!/usr/bin/env bash

# This library includes functions for setting up the interactive environment as
# well as functions that are intended for interactive use.

# Formatted cleancache stats
function ccmon {
	typeset i interval=${1:-.5}

	while :; do
		for i in /sys/kernel/mm/cleancache/*; do
			printf '%-15s %d\n' "${i##*/}:" "$(<"$i")"
		done
		sleep "$interval"
		clear
	done
}

# Set radeon power management
function clk {
	typeset base=/sys/class/drm/card0/device
	[[ -r ${base}/hwmon/hwmon0/temp1_input && -r ${base}/power_profile ]] || return 1

	case $1 in
		low|high|default)
			printf '%s\n' "temp: $(<${base}/hwmon/hwmon0/temp1_input)C" "old profile: $(<${base}/power_profile)"
			echo "$1" >${base}/power_profile
			echo "new profile: $(<${base}/power_profile)"
			;;
		*)
			echo "Usage: $FUNCNAME [ low | high | default ]"
			printf '%s\n' "temp: $(<${base}/hwmon/hwmon0/temp1_input)C" "current profile: $(<${base}/power_profile)"
	esac
}

function eapi {
	okular "$(equery f -f doc app-doc/pms:live | grep '.pdf$')" >/dev/null 2>&1 &
	disown
}

# List eix overlay numbers.
function eolist {
	OVERLAYS_LIST=all PRINT_COUNT_ALWAYS=never eix -!
}

function ksmtool {
	case $1 in
		enable) echo 1 >/sys/kernel/mm/ksm/run ;;
		disable) echo 0 >/sys/kernel/mm/ksm/run ;;
		stats) grep . /sys/kernel/mm/ksm/* ;;
		*)
			printf -- 'Invalid option: %s\n' "$1" >&2
			return 1
	esac
}

# Load kvm-related modules.
function kvmmodprobe {
	typeset x
	echo 'loading modules:' >&2

	{
		find "/lib/modules/$(uname -r)" -iname '*virtio*' -printf '%f\0'
		printf '%s\0' 9p # Additional modules.
	} | while IFS= read -rd '' x; do
			x=${x%.*}
			printf '%4s%s\n' '' "$x" >&2
			modprobe -- "$x"
		done
}

# Stupid game.
# minecraft -c | -s [ -p ]
function minecraft {
	typeset \
		jvm=${JAVA_HOME}/bin/java \
		worldPath=~/doc/mcdata2 \
		serverPath=~/doc/programs/ServerJarStorage/Release\ 1.8/minecraft_server.jar \
		clientPath=~/doc/programs/Minecraft.jar

	typeset opt OPTARG OPTIND OPTERR=0
	typeset -A mcopts

	[[ -x $jvm ]] || return

	while getopts :scp: opt; do
		case $opt in
			\?)
				printf 'Unknown option: %s\n' "$OPTARG" >&2
				return 1
				;;
			:)
				printf '-%s requires an argument.\n' "$OPTARG" >&2
				return 1
				;;
			*)
				mcopts[$opt]=$OPTARG
				OPTARG=
		esac
	done

	if ! ${mcopts[s]+false}; then # Server
		pushd "$worldPath" || return
		if ! ${mcopts[p]+false}; then # If user supplies a fifo then read from it.
			if [[ -p ${mcopts[p]} ]]; then
				 # Open the fifo without blocking using a temporary fd in case there's no writer.
				 {
					 {
						 #lsof -ap "$BASHPID" -d 0-20 +f G >&2
						 #cat
						 "$jvm" -Xmx4096M -jar "$serverPath" nogui
					 } 3<>"${mcopts[p]}" </dev/fd/3 3>&-
				 } &
			else
				prEintf '%s must be a readable/writable named pipe\n' "${mcopts[p]}" >&2
				return 1
			fi
		else
			"$jvm" -Xmx4096M -jar "$serverPath" nogui &
		fi
		printf 'Minecraft server PID: %d\n' "$!"
		wait
		popd
	elif ! ${mcopts[c]+false}; then # Client
		"$jvm" -jar "$clientPath"
	fi
}

# shortcut for default trayer options
function trayr {
	typeset -a opts=(
		--edge top
		--align right
		--SetDockType true
		--SetPartialStrut true
		--expand true
		--widthtype percent
		--width 15
		--transparent true
		--tint 0x000000
		--heighttype pixel
		--height 12
	)

	trayer-srg "${opts[@]}" & disown
}

# vim: set fenc=utf-8 ff=unix ft=sh :
