#!/bin/bash
# Copyright (C) 1999 - 2005, 2014 Red Hat, Inc. All rights reserved. This
# copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the
# GNU General Public License version 2.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Authors:
#	Yaakov Selkowitz <yselkowi@redhat.com>

shopt -s extglob lastpipe

function startJobsIfExecutable {
	typeset bin
	for bin; do
		[[ -x $bin ]] && "$bin" &
	done
}

function startFirstExecutable {
	typeset bin
	for bin; do
		if [[ -x $bin ]]; then
			"$bin" &
			return
		fi
	done

	return 1
}

# default settings
function settings {
	typeset x
	for x in /usr/bin/{xdg-user-dirs-gtk-update,gsettings-data-convert}; do
		"$x"
	done

	startJobsIfExecutable \
		/usr/libexec/{mate-notification-daemon,notification-daemon} \
		/usr/lib/xfce4/notifyd/xfce4-notifyd \
		/usr/bin/lxqt-notificationd

	if [[ -x /usr/bin/start-pulseaudio-x11 ]]; then
		/usr/bin/start-pulseaudio-x11
		startFirstExecutable /usr/bin/{pasystray,mate-volume-control-applet}
	fi

	if [[ -x /usr/bin/gnome-keyring-daemon ]]; then
		eval "$(/usr/bin/gnome-keyring-daemon --start)"
		export GNOME_KEYRING_CONTROL GPG_AGENT_INFO SSH_AUTH_SOCK
	fi

	[[ -x /usr/bin/krb5-auth-dialog ]] && /usr/bin/krb5-auth-dialog &

	startFirstExecutable /usr/libexec/evolution/3.{12,10}/evolution-alarm-notify
	startJobsIfExecutable /usr/bin/{seahorse-sharing,zeitgeist-datahub,xterm,fbxkb}
	[[ -x /usr/bin/fbpanel ]] && /usr/bin/fbpanel -p multiwindow &
}

function main {
	# redirect errors to a file in user's home directory if we can
	if [[ -z "$GDMSESSION" ]]; then
		# GDM redirect output itself in a smarter fashion
		typeset errfile="$HOME/.xsession-errors"
		if ( umask 077 && cp /dev/null "$errfile" 2> /dev/null ); then
			chmod 600 "$errfile"
			[[ -x /sbin/restorecon ]] && /sbin/restorecon "$errfile"
			exec >"$errfile" 2>&1
		else
			errfile=$(mktemp -q "/tmp/xses-${USER}.XXXXXX") && exec >"$errfile" 2>&1
		fi
	fi

	# Mandatorily source xinitrc-common, which is common code shared between the
	# Xsession and xinitrc scripts which has been factored out to avoid duplication
	. /etc/X11/xinit/xinitrc-common

	# The user may have their own clients they want to run.  If they don't,
	# fall back to system defaults.
	if [[ -f ${HOME}/.startxwinrc ]] ; then
		exec "$CK_XINIT_SESSION" "$SSH_AGENT" "${HOME}/.startxwinrc" ||
		exec "$CK_XINIT_SESSION" "$SSH_AGENT" "${HOME}/.startxwinrc"
	else
		setup "$@"
	fi
}

main "$@"
